spring:
  datasource:
    db-master:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mytest?serverTimezone=Asia/Shanghai&useSSL=true
      username: root
      password: 123456
    db-read:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/mytest2?serverTimezone=Asia/Shanghai&useSSL=true
     username: root
     password: 123456
  aop:
    auto: true